#!/usr/bin/env ruby

# sync output
$stdout.sync = true

$:.unshift File.expand_path("../lib", __FILE__)
require "pebble_receiver"

# username, key
# returns exit code, 0 for success
exit PebbleReceiver::Auth.start(ARGV[0], ARGV[1])
