#!/bin/bash

if [ -f /gopath/bin/gitreceived ];
then
  /gopath/bin/gitreceived -r /tmp/pebble-repos -k /ssh_host_rsa_key /scripts/auth /scripts/receiver
else
  SSH_PRIVATE_KEYS="${SSH_PRIVATE_KEYS:="`sudo cat /etc/ssh/ssh_host_rsa_key`"}"
  export SSH_PRIVATE_KEYS="$SSH_PRIVATE_KEYS"
  export MIKE_PORT_5000_TCP_ADDR="localhost"
  export MIKE_PORT_5000_TCP_PORT="5000"
  export MIKE_AUTH_KEY="99ca3e26c5691b289c9ce5c1d0d77b9bc890179ac27283386777e95b2cc0e46a"
  gitreceived -p 2221 -r /tmp/pebble-repos ./scripts/auth ./scripts/receiver
fi
